---
#- name: download wordpress
#  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=~/wordpress-{{ wp_version }}.tar.gz

- name: download and extract wordpress config
#  command: chdir=~ /bin/tar xvf wordpress-{{ wp_version }}.tar.gz creates=~/wordpress
  unarchive:
    src: http://wordpress.org/wordpress-{{ wp_version }}.tar.gz
    dest: /tmp
    remote_src: yes

- name: copy wordpress to apache root directory
  shell: cp -r /tmp/wordpress/* /var/www/html

- name: fetch random salts for wordpress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
#  get_url: url=https://api.wordpress.org/secret-key/1.1/salt/ dest=./
  register: "wp_salt"

- name: create wordpress database
  mysql_db: name={{ wp_db_name }} state=present

- name: create wordpress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present

- name: copy wordpress config file
  template: src=wp-config.php dest=/var/www/html/

- name: change ownership of wordpress installation
  file: path=/var/www/html/ owner=apache group=apache state=directory recurse=yes
