---
- name: install mysql server
  yum: name=mariadb-server state=present
- name: install mysql devel
  yum: name=mariadb-devel state=present

- name: install python-devel
  yum: name=python-devel state=present

- name: install mysql-python
  pip: name=mysql-python state=present

- name: create mysql conf file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: restart mysql

- name: start mysql service
  service: name=mariadb state=started enabled=true
